dockerfile: |-
  RUN apk add --no-cache build-base git
  RUN gem update --system
  RUN gem install gem_hadar bundler
fail_fast: true
script: &script |-
  echo -e "\e[1m"
  ruby -v
  echo -e "\e[0m"
  bundle
  rake test

images:
  ruby:3.3-alpine: *script
  ruby:3.2-alpine: *script
  ruby:3.1-alpine: *script
  ruby:3.0-alpine: *script
  ruby:2.7-alpine: *script
  ruby:2.6-alpine: *script
